#!/bin/sh
# License: BSD (3 clause)
# Author: Kris Moore <kris@trueos.org>
# Comment: anacron script, called periodically to start updates

PATH="${PATH}:/usr/local/bin:/usr/local/sbin"

trueos_ETCCONF="/usr/local/etc/trueos.conf"
export trueos_ETCCONF

# Available settings
# all - Will upgrade to new major releases, security and pkg
# disabled - Don't do ANY automatic updates
AUTO_UPDATE="all"

check_pkg()
{
  pc-updatemanager pkgcheck >/dev/null 2>/dev/null
  rtn=$?
  if [ $rtn -eq 100 ] ; then
     sleep $waittime
     # We have a pkg update! Lets start it now
     nice pc-updatemanager pkgupdate >/var/log/pc-updatemanager-auto.log 2>/var/log/pc-updatemanager-auto.log
     exit 0
  fi
}

if [ `id -u` != "0" ] ; then exit 1 ; fi

# If we already have done an update, and are ready to reboot, don't kickoff another
if [ -e "/tmp/.rebootRequired" ] ; then
   if [ "`cat /tmp/.rebootRequired`" = "`who -b`" ] ; then
     exit 0
   fi
fi

# Check if updates are already running
if [ -e "/tmp/.updateInProgress" ] ; then
   pgrep -F /tmp/.updateInProgress >/dev/null 2>/dev/null
   if [ $? -eq 0 ] ; then exit 0; fi
fi

# Check if we are currently booted into the default BE
# This stops auto-updates if manually booted into another BE
beadm list | grep -q "NR "
if [ $? -ne 0 ] ; then
  exit 0
fi

waittime=$(jot -r 1 1 3600)

_upChk="`sed -n 's/AUTO_UPDATE: //p' ${trueos_ETCCONF} 2>/dev/null | awk '{print $1}'`"
if [ -n "${_upChk}" ] ; then AUTO_UPDATE="$_upChk" ; fi

case $AUTO_UPDATE in
           all) check_pkg ;;
      disabled) # Do nothing
                ;;
   *) echo "Invalid AUTO_UPDATE setting detected! Please fix /usr/local/etc/trueos.conf"
      exit 1
      ;; 
esac

exit 0
