#!/bin/sh
#
# Copyright (c) 2017 TrueOS / iXsystems
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# We are doing a major upgrade!
TERM="cons25" ; export TERM
export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"

if [ -e "/var/.pc-attempt1" ] ; then
   echo "The previous upgrade attempt failed!"
   echo "Rolling back to last known good BE..."
   oldBE=`cat /var/.lastGoodBE`
   /etc/beadm activate $oldBE   
fi

# Set indicator that this is first attempt at upgrading
touch /var/.pc-attempt1

if [ ! -d "/usr/local/log/pc-updatemanager" ] ; then
   mkdir -p /usr/local/log/pc-updatemanager
fi
OLOG="/usr/local/log/pc-updatemanager/upgrade.log"
clear

# If the update left us without /root/.cshrc /root/.profile, due to hard-link funk, fix it
if [ ! -e "/root/.cshrc" ] ; then
  cp /.cshrc /root/.cshrc
fi
if [ ! -e "/root/.profile" ] ; then
  cp /.profile /root/.profile.
fi

echo "Preparing to do pkg installation..."
sleep 5

clear
sh /.doPkgUp.sh 2>&1 | tee -a $OLOG
sync
rm /.doPkgUp.sh

# Post update scripts
UPDATEDOTDPOST="/usr/local/etc/pcupdate.d/post"
if [ -d "${UPDATEDOTDPOST}" ] ; then
  for post in `ls ${UPDATEDOTDPOST}`
  do
    if [ "$post" = "README" ] ; then continue ; fi
    echo "Running post-update script: $post"
    sh ${UPDATEDOTDPOST}/${post} "$1"
    if [ $? -ne 0 ] ; then
       echo "WARNING: Failed running post-update script: $post"
    fi
  done
fi

# Move the original RC files back
mv /etc/rc-orig /etc/rc
rm /etc/rc-update
rm /etc/rc-doupdate
rm /etc/beadm
rm /var/.pc-attempt1

echo "Finished pkg installation.. Preparing to reboot...."
sleep 10
   
clear
echo "Rebooting..."
/sbin/reboot
